### PR TITLE
Fix `is_module_fusible()` bug in MIGraphX 

### LINKED ISSUE #3079: Add Splitk GEMM test that would split pointwise module
k<=1024 for MIGraphX to pick MLIR by default. 

Some GEMM configs that has higher probablity of picking split-k config from MLIR are as follows: 

-g 1 -m 2 -n 1280 -k 2816
-g 1 -m 2 -n 1280 -k 1280
-g 1 -m 2 -n 1280 -k 320
-g 1 -m 32 -n 64 -k 1024

Exhaustive-tune needs to be enabled for the split-k to be picked.

### PR DESCRIPTION
**Pull request by umangyadav**
`is_module_fusible()` needs to be run after `run_highlevel_pipeline()` otherwise it always returns True. 

Enable test for the split-k + pointwise by turning on exhaustive-tune for the `gemm_add` test.

Also fixes #3079

### CODE REVIEW

File: src/targets/gpu/mlir.cpp [hunk 1]
```diff
@@ -947,10 +947,12 @@ struct mlir_program
     std::string sym_name;
 };
 
-bool is_module_fusible(const module& m, const value& solution)
+bool is_module_fusible(const module& m, const context& migraphx_ctx, const value& solution)
 {
     mlir_program mp;
+    mp.set_gpu_properties(migraphx_ctx);
```
Comment (pfultz2) [inline src/targets/gpu/mlir.cpp:953]: Does gpu properties need to be set for the high level pipeline?

Comment (umangyadav) [reply src/targets/gpu/mlir.cpp:953]: Yes otherwise MLIR prints warnings like 
`Warning: unknown architecture, falling back to defaults:`

**Review by TedThemistokleous — APPROVED** [review]
Outside of Paul's question this makes sense.

File: src/targets/gpu/mlir.cpp (hunk 1 above)
Comment (pfultz2) [reply src/targets/gpu/mlir.cpp:953]: But is that a problem for `is_module_fusible`?

Comment (umangyadav) [reply src/targets/gpu/mlir.cpp:953]: `set_gpu_properties` is only setting the `arch` on the MLIR function. MLIR can potentially run different route while running high level backend pipeline. 

Also we don't want warnings that can be fixed.

Comment (pfultz2) [reply src/targets/gpu/mlir.cpp:953]: I assume the high level pipeline is target independent so it seems unnecessary, but this would be a better question for @sjw36 @krzysz00 @manupak to answer.

Comment (umangyadav) [reply src/targets/gpu/mlir.cpp:953]: MLIR team can answer it, but i don't see why this issue would be a blocker for approval. I don't see any harm in having a call to `set_target_properties()` and setting `arch` attribute.  arch is set later too when compiling MLIR module.

Comment (manupak) [reply src/targets/gpu/mlir.cpp:953]: > I assume the high level pipeline is target independent so it seems unnecessary.

In a practical sense yes, but we do extract features from arch in the high-level; so that further lowerings (low-level) only look at a bag of features that is there on the arch.

**Review by pfultz2 — APPROVED** [review]
