### PR TITLE
g+g disabling for navi/f32, sort fix, force gemm0 to be first input of gemm1, toggle off intermediate outs

### LINKED ISSUE #4371: Don't offload GEG/CEG kernels to rocMLIR for f32 on navi3x
### DOR (Definition of Ready)

Ready

### Description

rocMLIR doesn't support attention like kernels. eg. GEG, Attention, CEG if there is no associated wmma/mfma instruction for that dtype on the hardware. The only current known case is fp32 on navi3x. 

In MIGraphX, we treat GEG/CEG and attention differently. This issue is for GEG/CEG specifically; attention is covered by #4308 which is less trivial than this case.

### DOD (Definition of Done)

CEG/GEG kernels are not generated for unsupported dtype/hardware combos

### LINKED ISSUE #4386: rocmlir g+g only supports (A*B)*C, not C*(A*B)
The current implementation of g+g fusion on the migraphx side does not force any specific ordering of the second gemm's inputs. As a result, both of these will be sent to rocmlir:
gemm0 = (m, k) x (k, n) = (m, n)
gemm1 = (m, n ) x (n, n2) OR (m2, m) x (m, n)

(m2, m) x (m, n) should not be sent, at least as-is, to rocmlir. It either needs to not be matched, or a transpose needs to be inserted.

### LINKED ISSUE #4394: G+G: toggle off multi-user intermediates & crawl for use cases
MIGraphX is currently allowing g+g fusions to have multi-users for the gemm0 and pointwise intermediates. Also currently, rocMLIR does *not* support this.
  

- [ ] crawl tier 1 and tier 2 models to see how common this case is. Probably want to run the fusion and then see how many geg kernels return more than one output  
- [ ] toggle off the support for now  
- [ ] report to rocMLIR the script results

### PR DESCRIPTION
**Pull request by bdevorem**
I decided to split up these PRs, so this PR is missing the commits to add heuristic-based enabling.

Closes #4371
Closes #4394
Closes #4386

## Motivation
1. Currently, g+g fusion is turned off for all the rnn tests to get around attention-like kernels failing on navi when the dtype is f32. This gets rid of that stop-gap and solves it properly, by checking the validity of gemms in the g+g matcher. I have confirmed with rocMLIR that neither gemm should be f32 in this case.
2. There is a bug in my `localized_sort` that was exposed by 1 above. It is now fixed.
3. I have learned from rocMLIR that g+g is only supported when the dependency chain is along the first input to the second gemm; the second input being the chain is not supported. This fixes that.
4. I have learned from rocMLIR that multi-out intermediates is not currently supported. This toggles it off.

## Technical Details

1. I added the gfx name to the matcher, and added a predicate for checking if a gemm/conv is f32 when gfx starts with gfx11 or gfx12. I also changed all the fuse_mlir tests to be fp16 so that those tests will always run, even if on navi.
2. The previous assumption was that the moving of instructions not in the dependency chain would include the inputs. This is not accurate, which results in any op not directly in the chain of instructions between gemm0 and gemm1 to be moved to gemm0, *including* users of the intermediate values. Now, it also checks if any of its inputs are positionally after the start of the dependency chain before moving. Since it goes in positional order, and the graph is already topologically sorted, all instructions that can be moved before gemm0, will be, and not otherwise. So, when we come across an instruction that is a user of one of the ops in the chain, it will not move. Then, any op following it that is dependent will also not move. I also added an assertion that I should have had originally.  
This solution works because the fusion is not applied to graphs where there is a circle, kind of, i.e. the elementwise having two inputs that reach gemm0, etc. Previously, I only checked if gemm1 had more than one input dependent upon the elementwise, but it also needs to check the same for gemm0, so I've added that too. This also currently is not in use; rocMLIR does not support multi-out intermediates for g+g (see below), and this sort is only needed in that use case.
3. Instead of letting the pointwise op be in any input slot of the second gemm, this will only match if it is the first input. I also added tests to confirm that ABC is supported and CAB is not.
4. I have added a flag in the fuse_mlir class that toggles if multi out intermediates is supported for g+g. It defaults to false, and only the tests testing if the migraphx side of this works has the flag set to true. I edited the test file to allow the flag to be set to the pass class.

## Changelog Category

- - [x] Added: New functionality.
- - [x] Changed: Changes to existing functionality.
- - [ ] Removed: Functionality or support that has been removed. (Compared to a previous release)
- - [ ] Optimized: Component performance that has been optimized or improved.
- - [x] Resolved Issues: Known issues from a previous version that have been resolved.
- - [ ] Not Applicable: This PR is not to be included in the changelog.

### CODE REVIEW

**Comment by bdevorem** [comment]
~I am expecting one failure for mlir_debug right now, `test_verify test_rnn_4args*`, (and similarly `test_rnn_reverse/forward`) due to an untuned problem config. I am discussing with rocMLIR to resolve.~

Resolved

File: src/targets/gpu/fuse_mlir.cpp [hunk 1]
```diff
@@ -788,6 +788,23 @@ struct find_mlir_fused_geg_ops
...
     mlir_mode conv_mode = mlir_mode::none;
     mlir_mode dot_mode  = mlir_mode::none;
+    std::string gfx_name;
+    bool enable_geg_multi_out_intermediates = false;
+
+    // check if individual GEMM meets architecture requirements
+    bool is_gemm_supported(instruction_ref ins) const
+    {
+        // on navis, wmma doesn't support fp32, so skip fp32 GEMMs
+        // one gemm being f32 is sufficient to turn off this fusion
```
Comment (TedThemistokleous) [inline src/targets/gpu/fuse_mlir.cpp:798]: appreciate the comment here

File: test/gpu/fuse_mlir.cpp [hunk 2]
```diff
@@ -52,10 +52,13 @@ struct non_mlir_op
     }
 };
 
-static void run_pass(migraphx::program& p)
+static void run_pass(migraphx::program& p, bool enable_geg_multi_user = false)
```
Comment (pfultz2) [inline test/gpu/fuse_mlir.cpp]: I would do `migraphx::gpu::fuse_mlir fm = {}`, so it can be called as `run_pass(p1, {.enable_geg_multi_out_intermediates = true})`

File: src/module.cpp [hunk 3]
```diff
@@ -1614,15 +1614,33 @@ void module::localized_sort(instruction_ref start_ins, instruction_ref end_ins)
...
+            {
+                // input is after start_ins, meaning can't move this instruction
+                ++it;
+            }
+            else
+            {
+                auto next = std::next(it);
+                this->move_instruction(it, start_ins);
+                it = next;
+            }
```
Comment (pfultz2) [inline src/module.cpp:1636]: Can we add unit tests for this function? I am also thinking `localized_sort` is not the best name since it seems more like to move the instructions then sort them.

Comment (bdevorem) [reply src/module.cpp:1636]: There's a couple already on develop but I'll add more

**Review by pfultz2 — APPROVED** [review]
